### ISSUE TITLE
Koodin katselmointi II

### ISSUE THREAD

**Issue by pparm** [iilumme/Tsoha-Bootstrap#2]
Hienolta työltä vaikuttaa. Persoonallinen käyttöliittymä ja harkkatyöksi valtavasti toiminnallisuuksia ja ominaisuuksia. Tässä katselmuksessa testattiin järjestelmää.

Testauksessa havaittuja bugeja  ja huomioita käytettävyyden parantemiseksi. Näin laajan harjoitustyö on varmasti kesken:
1. 15.3. klo 16.19 kirjautuja: pelle salasana: pelle muokkaa omia tiedostoja tulee herja.
   http://iilumme.users.cs.helsinki.fi/tsoha/mypage/edit
   "Type: ErrorException
   Code: 2
   Message: Missing argument 1 for Kayttaja::update(), called in /home/iilumme/htdocs/tsoha/app/controllers/user_controller.php on line 104 and defined
   File: /home/iilumme/htdocs/tsoha/app/models/Kayttaja.php
   Line: 80"
2. 15.3. klo 16.33 kun käyttäjänä lisäsi elokuvaa meni hetki aikaa, ennen kuin tajusi, että ensin tulee elokuvan kohdalla painaaa "lisää elokuva". Tämän jälkeen ei näkynyt mitään. Elokuva tulivat esille painaessa uudestaan toista nappia "lisää elokuvat". Tämäkin lienee vielä kehityksen alla.
3. Vaikuttaisi siltä, että rekisteröitynyt käyttäjä pääsee käsiksi kaikkiin toiminnalisuuuksiin, vaikka kuvauksessa puhuttiin rajoituksista. Sessiot eivät taida olla täysin käytössä ja ainakaan BaseControl luokassa ei ole metodia ohjaajan session tarkistuseen.
4. Hakutoimminnossa jäin kaipaamaan elokuvan nimellä hakua. Tähän ei kannattane käyttää resursseja.
5. Taulut vaikuttavat järkeviä ja en havainnut niissä loogisia virheitä. Koodi oli selkeätä ja  ymmärrettävää. Jonkun verran oli metodien nimissä englantia ja suomea sekaisin. En lähtisi niitä muuttamaan.

Hieno työ jossa on valokuvia, hakuominaisuuksia. Käyttöliittymä ei ehkä täytä kaikkia HCI:n ja kognitiotieteen oppikirjaratkaisuja. Se on kuitenkin hauska ja tehty pilke silmäkulmassa. Jos joskus elämässä joutuu suunnittelemaan ja toteuttamaan käyttöliittymiä oikeasti, kannattanee vain kopioida muiden tekemiä ratkaisuja.

En laajentaisi työtä enää lainkaan, vaan karsisin turhat toiminnallisuudet pois, testaisin, pitäisin demon ja pushaisin lopullisen palautuksen sisään;)

**Comment by iilumme** [comment]
@pparm Kiitos kommenteista! :D Kysyisin vain tuosta kohdasta 2, että mistä elokuvan lisäyksestä on kyse? Käyttäjän omille listoille vai ihan tietokantaan lisäämisestä? :)
